/* facade.c — the C ABI (csson.h) over the embedded QuickJS + CSSON JS bundle.
 *
 * This is the ONLY C in libcsson now: it embeds QuickJS-ng, evaluates the bundle
 * (PostCSS + csstree + our TypeScript) once into a persistent context, sets the
 * four engine limits, and marshals strings across the boundary. All CSSON logic
 * lives in the TypeScript (ts/csson.ts); nothing here parses or processes CSS.
 *
 * Thread-safety: this single-context facade is NOT reentrant. For concurrent use,
 * a binding creates one runtime per thread (proven safe; see the rebuild plan).
 */
// NOLINTNEXTLINE(bugprone-reserved-identifier): POSIX strdup
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "quickjs.h"
#include "../include/csson.h"
#include "csson_bundle.h" /* generated by tools/build-bundle.mjs */

/* The four engine limits that bound any single call (attackers control data, not
 * code, so these cap resource use on hostile input):
 *   1. heap cap      JS_SetMemoryLimit
 *   2. stack cap     JS_SetMaxStackSize  (deep nesting -> clean RangeError)
 *   3. wall-clock    interrupt handler   (ReDoS / runaway loop -> InterruptError)
 *   4. input size    rejected before it ever reaches the engine
 */
#define CSSON_HEAP_LIMIT ((size_t)512 << 20)    /* 512 MiB */
#define CSSON_STACK_LIMIT ((size_t)4 << 20)     /* 4 MiB   */
#define CSSON_TIME_LIMIT_MS 5000                /* 5 s per call */
#define CSSON_MAX_INPUT ((size_t)256 << 20)     /* 256 MiB */

static JSRuntime *RT;
static JSContext *CTX;

/* limit 3: a per-call wall-clock deadline. Armed around each JS_Call; the engine
 * calls on_interrupt() periodically during execution, which aborts once past it. */
static struct timespec g_deadline;
static bool g_armed;

static int on_interrupt(JSRuntime *rt, void *opaque) {
    (void)rt;
    (void)opaque;
    if (!g_armed)
        return 0;
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    if (now.tv_sec > g_deadline.tv_sec ||
        (now.tv_sec == g_deadline.tv_sec && now.tv_nsec >= g_deadline.tv_nsec))
        return 1; /* past deadline -> interrupt with InterruptError */
    return 0;
}

static void arm_deadline(void) {
    clock_gettime(CLOCK_MONOTONIC, &g_deadline);
    g_deadline.tv_sec += CSSON_TIME_LIMIT_MS / 1000;
    g_deadline.tv_nsec += (CSSON_TIME_LIMIT_MS % 1000) * 1000000L;
    if (g_deadline.tv_nsec >= 1000000000L) {
        g_deadline.tv_sec += 1;
        g_deadline.tv_nsec -= 1000000000L;
    }
    g_armed = true;
}

/* Tear the persistent singleton down at process exit so nothing is left in use
 * (memcheck target: 0 bytes in use at exit). Registered with atexit in init. */
static void facade_shutdown(void) {
    if (CTX) {
        JS_FreeContext(CTX);
        CTX = nullptr;
    }
    if (RT) {
        JS_FreeRuntime(RT);
        RT = nullptr;
    }
}

static void facade_init(void) {
    RT = JS_NewRuntime();
    JS_SetMemoryLimit(RT, CSSON_HEAP_LIMIT);   /* limit 1: heap cap */
    JS_SetMaxStackSize(RT, CSSON_STACK_LIMIT); /* limit 2: stack (deep input -> RangeError) */
    JS_SetInterruptHandler(RT, on_interrupt, nullptr); /* limit 3: wall-clock deadline */
    atexit(facade_shutdown);
    CTX = JS_NewContext(RT);
    JSValue v = JS_Eval(CTX, (const char *)csson_bundle, csson_bundle_len, "<csson>",
                        JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(v)) {
        JSValue e = JS_GetException(CTX);
        const char *s = JS_ToCString(CTX, e);
        fprintf(stderr, "csson: engine init failed: %s\n", s ? s : "?");
        JS_FreeCString(CTX, s);
        JS_FreeValue(CTX, e);
        abort();
    }
    JS_FreeValue(CTX, v);
}

static void ensure(void) {
    if (!RT)
        facade_init();
}

/* Call csson.<method>(arg0[, a1, a2, a3]); arg0 is (src,len), the rest NUL-term.
 * Returns the JS result string (owned, via strdup) or nullptr with *err set. */
static char *invoke3(const char *method, const char *src, size_t len, const char *a1,
                     const char *a2, const char *a3, char **err) {
    if (len > CSSON_MAX_INPUT) { /* limit 4: reject before it reaches the engine */
        if (err)
            *err = strdup("input exceeds the maximum size");
        return nullptr;
    }
    ensure();
    JSValue g = JS_GetGlobalObject(CTX);
    JSValue csson = JS_GetPropertyStr(CTX, g, "csson");
    JSValue fn = JS_GetPropertyStr(CTX, csson, method);
    JSValue argv[4];
    int n = 0;
    argv[n++] = JS_NewStringLen(CTX, src, len); /* binary-safe (embedded NUL ok) */
    if (a1)
        argv[n++] = JS_NewString(CTX, a1);
    if (a2)
        argv[n++] = JS_NewString(CTX, a2);
    if (a3)
        argv[n++] = JS_NewString(CTX, a3);
    arm_deadline();
    JSValue r = JS_Call(CTX, fn, csson, n, argv);
    g_armed = false;
    char *out = nullptr;
    if (JS_IsException(r)) {
        JSValue e = JS_GetException(CTX);
        const char *m = JS_ToCString(CTX, e);
        if (err)
            *err = m ? strdup(m) : strdup("error");
        JS_FreeCString(CTX, m);
        JS_FreeValue(CTX, e);
    } else {
        const char *s = JS_ToCString(CTX, r);
        if (s)
            out = strdup(s);
        JS_FreeCString(CTX, s);
    }
    for (int i = 0; i < n; i++)
        JS_FreeValue(CTX, argv[i]);
    JS_FreeValue(CTX, r);
    JS_FreeValue(CTX, fn);
    JS_FreeValue(CTX, csson);
    JS_FreeValue(CTX, g);
    return out;
}

/* Two- and one-extra-arg shims over invoke3. */
static char *invoke(const char *method, const char *src, size_t len, const char *a1, const char *a2,
                    char **err) {
    return invoke3(method, src, len, a1, a2, nullptr, err);
}

char *csson_to_canonical_json(const char *src, size_t len, char **err) {
    return invoke("toCanonicalJson", src, len, nullptr, nullptr, err);
}
char *csson_get(const char *src, size_t len, const char *pointer, char **err) {
    return invoke("get", src, len, pointer, nullptr, err);
}
char *csson_from_json(const char *json, size_t len, char **err) {
    return invoke("fromJson", json, len, nullptr, nullptr, err);
}
char *csson_set(const char *src, size_t len, const char *pointer, const char *value, char **err) {
    return invoke("set", src, len, pointer, value, err);
}
char *csson_set_json(const char *src, size_t len, const char *pointer, const char *json_value,
                     char **err) {
    return invoke("setJson", src, len, pointer, json_value, err);
}
char *csson_remove(const char *src, size_t len, const char *pointer, char **err) {
    return invoke("remove", src, len, pointer, nullptr, err);
}
char *csson_patch(const char *src, size_t len, const char *patch_json, char **err) {
    return invoke("patch", src, len, patch_json, nullptr, err);
}

int csson_validate(const char *syntax, const char *value, char **err) {
    char *r = invoke("validate", syntax ? syntax : "", strlen(syntax ? syntax : ""), value, nullptr,
                     err);
    if (!r)
        return -1;
    int ok = strcmp(r, "true") == 0;
    free(r);
    return ok;
}

/* ---- CSSOM-style handle API ------------------------------------------------
 * A csson_sheet owns the current source bytes; a csson_rule is (sheet, index
 * path) addressing the raw rule tree. Read/edit ops re-parse in TS via invoke3;
 * edit ops get the new source back and store it on the sheet, so comments
 * survive and existing handles stay valid (indices may shift, like the CSSOM).
 */
struct csson_sheet {
    char *src;
    size_t len;
    csson_rule **rules; /* owned handles, freed at close */
    size_t nrules, caprules;
};
struct csson_rule {
    csson_sheet *sheet;
    char *path; /* JSON index array, e.g. "[]" or "[0,2,1]" */
};

static csson_rule *sheet_track(csson_sheet *s, char *path) {
    if (!path)
        return nullptr;
    if (s->nrules == s->caprules) {
        size_t cap = s->caprules ? s->caprules * 2 : 8;
        csson_rule **r = realloc(s->rules, cap * sizeof *r);
        if (!r) {
            free(path);
            return nullptr;
        }
        s->rules = r;
        s->caprules = cap;
    }
    csson_rule *rule = malloc(sizeof *rule);
    if (!rule) {
        free(path);
        return nullptr;
    }
    rule->sheet = s;
    rule->path = path;
    s->rules[s->nrules++] = rule;
    return rule;
}

/* Append index `i` to a parent path string: "[]"+1 -> "[1]"; "[0,2]"+1 -> "[0,2,1]". */
static char *path_append(const char *parent, size_t i) {
    char num[32];
    int nn = snprintf(num, sizeof num, "%zu", i);
    if (nn < 0)
        return nullptr;
    size_t plen = strlen(parent);
    bool empty = (plen == 2); /* "[]" */
    char *out = malloc(plen + (size_t)nn + 2);
    if (!out)
        return nullptr;
    char *p = out;
    *p++ = '[';
    if (!empty) {                          /* copy existing indices (without the [ ]) */
        memcpy(p, parent + 1, plen - 2);
        p += plen - 2;
        *p++ = ',';
    }
    memcpy(p, num, (size_t)nn);
    p += nn;
    *p++ = ']';
    *p = 0;
    return out;
}

csson_sheet *csson_open(const char *src, size_t len, char **err) {
    /* Validate it parses + has a root by running a canon read once. */
    char *probe = csson_to_canonical_json(src, len, err);
    if (!probe)
        return nullptr;
    free(probe);
    csson_sheet *s = calloc(1, sizeof *s);
    if (!s) {
        if (err)
            *err = strdup("out of memory");
        return nullptr;
    }
    s->src = malloc(len ? len : 1);
    if (!s->src) {
        free(s);
        if (err)
            *err = strdup("out of memory");
        return nullptr;
    }
    memcpy(s->src, src, len);
    s->len = len;
    return s;
}

char *csson_sheet_text(const csson_sheet *sheet) {
    if (!sheet)
        return nullptr;
    char *out = malloc(sheet->len + 1);
    if (!out)
        return nullptr;
    memcpy(out, sheet->src, sheet->len);
    out[sheet->len] = 0;
    return out;
}

void csson_close(csson_sheet *sheet) {
    if (!sheet)
        return;
    for (size_t i = 0; i < sheet->nrules; i++) {
        free(sheet->rules[i]->path);
        free(sheet->rules[i]);
    }
    free(sheet->rules);
    free(sheet->src);
    free(sheet);
}

csson_rule *csson_root(csson_sheet *sheet) {
    if (!sheet)
        return nullptr;
    return sheet_track(sheet, strdup("[]"));
}

/* read-side helpers: call the TS handle op against the sheet's current source. */
static char *rule_call(csson_rule *rule, const char *method, const char *a2, const char *a3,
                       char **err) {
    return invoke3(method, rule->sheet->src, rule->sheet->len, rule->path, a2, a3, err);
}

size_t csson_rule_count(csson_rule *rule) {
    if (!rule)
        return 0;
    char *r = rule_call(rule, "hRuleCount", nullptr, nullptr, nullptr);
    size_t n = r ? strtoul(r, nullptr, 10) : 0;
    free(r);
    return n;
}

csson_rule *csson_rule_at(csson_rule *rule, size_t i) {
    if (!rule)
        return nullptr;
    return sheet_track(rule->sheet, path_append(rule->path, i));
}

char *csson_selector_text(csson_rule *rule) {
    if (!rule)
        return nullptr;
    return rule_call(rule, "hSelector", nullptr, nullptr, nullptr);
}

size_t csson_property_count(csson_rule *rule) {
    if (!rule)
        return 0;
    char *r = rule_call(rule, "hPropCount", nullptr, nullptr, nullptr);
    size_t n = r ? strtoul(r, nullptr, 10) : 0;
    free(r);
    return n;
}

char *csson_property_name_at(csson_rule *rule, size_t i) {
    if (!rule)
        return nullptr;
    char idx[32];
    snprintf(idx, sizeof idx, "%zu", i);
    return rule_call(rule, "hPropNameAt", idx, nullptr, nullptr);
}

char *csson_get_property(csson_rule *rule, const char *name) {
    if (!rule || !name)
        return nullptr;
    return rule_call(rule, "hGetProp", name, nullptr, nullptr); /* NULL = absent */
}

char *csson_get_property_value(csson_rule *rule, const char *name) {
    if (!rule || !name)
        return nullptr;
    return rule_call(rule, "hGetPropValue", name, nullptr, nullptr);
}

/* edit-side helper: run the TS edit, store the returned new source on the sheet. */
static int rule_edit(csson_rule *rule, const char *method, const char *a2, const char *a3,
                     char **err) {
    char *out = rule_call(rule, method, a2, a3, err);
    if (!out)
        return -1;
    char *dup = malloc(strlen(out) + 1);
    if (!dup) {
        free(out);
        if (err)
            *err = strdup("out of memory");
        return -1;
    }
    size_t n = strlen(out);
    memcpy(dup, out, n + 1);
    free(out);
    free(rule->sheet->src);
    rule->sheet->src = dup;
    rule->sheet->len = n;
    return 0;
}

int csson_set_property(csson_rule *rule, const char *name, const char *json_value, char **err) {
    if (!rule || !name || !json_value) {
        if (err)
            *err = strdup("null argument");
        return -1;
    }
    return rule_edit(rule, "hSetProp", name, json_value, err);
}

int csson_remove_property(csson_rule *rule, const char *name, char **err) {
    if (!rule || !name) {
        if (err)
            *err = strdup("null argument");
        return -1;
    }
    return rule_edit(rule, "hRemoveProp", name, nullptr, err);
}

int csson_insert_rule(csson_rule *parent, const char *text, long index, char **err) {
    if (!parent || !text) {
        if (err)
            *err = strdup("null argument");
        return -1;
    }
    char idx[32];
    snprintf(idx, sizeof idx, "%ld", index);
    return rule_edit(parent, "hInsertRule", text, idx, err);
}

int csson_delete_rule(csson_rule *parent, size_t index, char **err) {
    if (!parent) {
        if (err)
            *err = strdup("null argument");
        return -1;
    }
    char idx[32];
    snprintf(idx, sizeof idx, "%zu", index);
    return rule_edit(parent, "hDeleteRule", idx, nullptr, err);
}

const char *csson_supported_versions(void) {
    return "1";
}

void csson_free_string(char *s) {
    free(s);
}

/* csson_error_kind_of kept for ABI compatibility (the JS layer surfaces messages). */
csson_error_kind csson_error_kind_of(const char *err) {
    if (!err)
        return CSSON_OK;
    if (strstr(err, "no root"))
        return CSSON_E_NO_ROOT;
    if (strstr(err, "not valid JSON") || strstr(err, "JSON"))
        return CSSON_E_PARSE;
    if (strstr(err, "did not resolve") || strstr(err, "not found") ||
        strstr(err, "must address"))
        return CSSON_E_NOT_FOUND;
    if (strstr(err, "scalar") || strstr(err, "unsafe") || strstr(err, "representable"))
        return CSSON_E_VALUE;
    if (strstr(err, "patch") || strstr(err, "operation") || strstr(err, "test failed"))
        return CSSON_E_PATCH;
    return CSSON_E_OTHER;
}
