/* facade.c — the C ABI (csson.h) over the embedded QuickJS + CSSON JS bundle.
 *
 * This is the ONLY C in libcsson now: it embeds QuickJS-ng, evaluates the bundle
 * (PostCSS + csstree + our TypeScript) once into a persistent context, sets the
 * four engine limits, and marshals strings across the boundary. All CSSON logic
 * lives in the TypeScript (ts/csson.ts); nothing here parses or processes CSS.
 *
 * Thread-safety: this single-context facade is NOT reentrant. For concurrent use,
 * a binding creates one runtime per thread (proven safe; see the rebuild plan).
 */
// NOLINTNEXTLINE(bugprone-reserved-identifier): POSIX strdup
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "quickjs.h"
#include "../include/csson.h"
#include "csson_bundle.h" /* generated by tools/build-bundle.mjs */

/* The four engine limits that bound any single call (attackers control data, not
 * code, so these cap resource use on hostile input):
 *   1. heap cap      JS_SetMemoryLimit
 *   2. stack cap     JS_SetMaxStackSize  (deep nesting -> clean RangeError)
 *   3. wall-clock    interrupt handler   (ReDoS / runaway loop -> InterruptError)
 *   4. input size    rejected before it ever reaches the engine
 */
#define CSSON_HEAP_LIMIT ((size_t)512 << 20)    /* 512 MiB */
#define CSSON_STACK_LIMIT ((size_t)4 << 20)     /* 4 MiB   */
#define CSSON_TIME_LIMIT_MS 5000                /* 5 s per call */
#define CSSON_MAX_INPUT ((size_t)256 << 20)     /* 256 MiB */

static JSRuntime *RT;
static JSContext *CTX;

/* limit 3: a per-call wall-clock deadline. Armed around each JS_Call; the engine
 * calls on_interrupt() periodically during execution, which aborts once past it. */
static struct timespec g_deadline;
static bool g_armed;

static int on_interrupt(JSRuntime *rt, void *opaque) {
    (void)rt;
    (void)opaque;
    if (!g_armed)
        return 0;
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    if (now.tv_sec > g_deadline.tv_sec ||
        (now.tv_sec == g_deadline.tv_sec && now.tv_nsec >= g_deadline.tv_nsec))
        return 1; /* past deadline -> interrupt with InterruptError */
    return 0;
}

static void arm_deadline(void) {
    clock_gettime(CLOCK_MONOTONIC, &g_deadline);
    g_deadline.tv_sec += CSSON_TIME_LIMIT_MS / 1000;
    g_deadline.tv_nsec += (CSSON_TIME_LIMIT_MS % 1000) * 1000000L;
    if (g_deadline.tv_nsec >= 1000000000L) {
        g_deadline.tv_sec += 1;
        g_deadline.tv_nsec -= 1000000000L;
    }
    g_armed = true;
}

static void facade_init(void) {
    RT = JS_NewRuntime();
    JS_SetMemoryLimit(RT, CSSON_HEAP_LIMIT);   /* limit 1: heap cap */
    JS_SetMaxStackSize(RT, CSSON_STACK_LIMIT); /* limit 2: stack (deep input -> RangeError) */
    JS_SetInterruptHandler(RT, on_interrupt, nullptr); /* limit 3: wall-clock deadline */
    CTX = JS_NewContext(RT);
    JSValue v = JS_Eval(CTX, (const char *)csson_bundle, csson_bundle_len, "<csson>",
                        JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(v)) {
        JSValue e = JS_GetException(CTX);
        const char *s = JS_ToCString(CTX, e);
        fprintf(stderr, "csson: engine init failed: %s\n", s ? s : "?");
        JS_FreeCString(CTX, s);
        JS_FreeValue(CTX, e);
        abort();
    }
    JS_FreeValue(CTX, v);
}

static void ensure(void) {
    if (!RT)
        facade_init();
}

/* Call csson.<method>(arg0[, arg1, arg2]); arg0 is (src,len), the rest NUL-term.
 * Returns the JS result string (owned, via strdup) or nullptr with *err set. */
static char *invoke(const char *method, const char *src, size_t len, const char *a1,
                    const char *a2, char **err) {
    if (len > CSSON_MAX_INPUT) { /* limit 4: reject before it reaches the engine */
        if (err)
            *err = strdup("input exceeds the maximum size");
        return nullptr;
    }
    ensure();
    JSValue g = JS_GetGlobalObject(CTX);
    JSValue csson = JS_GetPropertyStr(CTX, g, "csson");
    JSValue fn = JS_GetPropertyStr(CTX, csson, method);
    JSValue argv[3];
    int n = 0;
    argv[n++] = JS_NewStringLen(CTX, src, len); /* binary-safe (embedded NUL ok) */
    if (a1)
        argv[n++] = JS_NewString(CTX, a1);
    if (a2)
        argv[n++] = JS_NewString(CTX, a2);
    arm_deadline();
    JSValue r = JS_Call(CTX, fn, csson, n, argv);
    g_armed = false;
    char *out = nullptr;
    if (JS_IsException(r)) {
        JSValue e = JS_GetException(CTX);
        const char *m = JS_ToCString(CTX, e);
        if (err)
            *err = m ? strdup(m) : strdup("error");
        JS_FreeCString(CTX, m);
        JS_FreeValue(CTX, e);
    } else {
        const char *s = JS_ToCString(CTX, r);
        if (s)
            out = strdup(s);
        JS_FreeCString(CTX, s);
    }
    for (int i = 0; i < n; i++)
        JS_FreeValue(CTX, argv[i]);
    JS_FreeValue(CTX, r);
    JS_FreeValue(CTX, fn);
    JS_FreeValue(CTX, csson);
    JS_FreeValue(CTX, g);
    return out;
}

char *csson_to_canonical_json(const char *src, size_t len, char **err) {
    return invoke("toCanonicalJson", src, len, nullptr, nullptr, err);
}
char *csson_get(const char *src, size_t len, const char *pointer, char **err) {
    return invoke("get", src, len, pointer, nullptr, err);
}
char *csson_from_json(const char *json, size_t len, char **err) {
    return invoke("fromJson", json, len, nullptr, nullptr, err);
}
char *csson_set(const char *src, size_t len, const char *pointer, const char *value, char **err) {
    return invoke("set", src, len, pointer, value, err);
}
char *csson_set_json(const char *src, size_t len, const char *pointer, const char *json_value,
                     char **err) {
    return invoke("setJson", src, len, pointer, json_value, err);
}
char *csson_remove(const char *src, size_t len, const char *pointer, char **err) {
    return invoke("remove", src, len, pointer, nullptr, err);
}
char *csson_patch(const char *src, size_t len, const char *patch_json, char **err) {
    return invoke("patch", src, len, patch_json, nullptr, err);
}

int csson_validate(const char *syntax, const char *value, char **err) {
    char *r = invoke("validate", syntax ? syntax : "", strlen(syntax ? syntax : ""), value, nullptr,
                     err);
    if (!r)
        return -1;
    int ok = strcmp(r, "true") == 0;
    free(r);
    return ok;
}

const char *csson_supported_versions(void) {
    return "1";
}

void csson_free_string(char *s) {
    free(s);
}

/* csson_error_kind_of kept for ABI compatibility (the JS layer surfaces messages). */
csson_error_kind csson_error_kind_of(const char *err) {
    if (!err)
        return CSSON_OK;
    if (strstr(err, "no root"))
        return CSSON_E_NO_ROOT;
    if (strstr(err, "not valid JSON") || strstr(err, "JSON"))
        return CSSON_E_PARSE;
    if (strstr(err, "did not resolve") || strstr(err, "not found") ||
        strstr(err, "must address"))
        return CSSON_E_NOT_FOUND;
    if (strstr(err, "scalar") || strstr(err, "unsafe") || strstr(err, "representable"))
        return CSSON_E_VALUE;
    if (strstr(err, "patch") || strstr(err, "operation") || strstr(err, "test failed"))
        return CSSON_E_PATCH;
    return CSSON_E_OTHER;
}
