/* qjs-compile.c — compile the CSSON JS bundle to QuickJS bytecode.
 *
 * MEASUREMENT / DEV TOOL — NOT part of the product build. The facade evaluates
 * the bundle as source; this tool exists to measure the bytecode alternative.
 * Finding: full bytecode is ~3.4x larger than the source bundle (3.7x gzipped);
 * even with STRIP_SOURCE+STRIP_DEBUG it is only ~size-neutral, and its sole
 * benefit (skip parse at startup) is not worth the version-lock. Kept so the
 * trade-off can be re-measured if cold-start latency ever justifies it.
 *
 * Links the SAME quickjs static lib the facade links, so the emitted bytecode is
 * version-matched to the engine. Reads the generated source array (csson_bundle.h),
 * compiles it (JS_EVAL_FLAG_COMPILE_ONLY), serializes with JS_WriteObject, and
 * writes a C header (csson_bytecode[] + csson_bytecode_len).
 *
 *   qjs-compile <out.h> [strip]      # "strip" drops source+debug info
 *
 * Build (against an existing native build's quickjs lib), e.g.:
 *   cc -std=c23 -O2 -Ibuild/quickjs -Ibuild/gen tools/qjs-compile.c \
 *      build/libquickjs.a -lm -o build/qjs-compile
 */
#define _POSIX_C_SOURCE 200809L
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "quickjs.h"
#include "csson_bundle.h" /* csson_bundle[] (JS source) + csson_bundle_len */

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: qjs-compile <out.h>\n");
        return 2;
    }
    JSRuntime *rt = JS_NewRuntime();
    JSContext *ctx = JS_NewContext(rt);

    JSValue fn = JS_Eval(ctx, (const char *)csson_bundle, csson_bundle_len, "<csson>",
                         JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
    if (JS_IsException(fn)) {
        JSValue e = JS_GetException(ctx);
        const char *m = JS_ToCString(ctx, e);
        fprintf(stderr, "qjs-compile: %s\n", m ? m : "compile failed");
        return 1;
    }

    size_t size = 0;
    int wflags = JS_WRITE_OBJ_BYTECODE;
    if (argc > 2 && argv[2][0] == 's') /* "strip": drop source + debug info */
        wflags |= JS_WRITE_OBJ_STRIP_SOURCE | JS_WRITE_OBJ_STRIP_DEBUG;
    uint8_t *buf = JS_WriteObject(ctx, &size, fn, wflags);
    if (!buf) {
        fprintf(stderr, "qjs-compile: JS_WriteObject failed\n");
        return 1;
    }

    FILE *out = fopen(argv[1], "wb");
    if (!out) {
        perror("fopen");
        return 1;
    }
    fputs("/* generated by tools/qjs-compile — do not edit */\n", out);
    fputs("static const unsigned char csson_bytecode[] = {", out);
    for (size_t i = 0; i < size; i++)
        fprintf(out, "%s%u,", (i % 20 == 0 ? "\n  " : ""), buf[i]);
    fputs("\n};\n", out);
    fprintf(out, "static const unsigned int csson_bytecode_len = %zu;\n", size);
    fclose(out);

    fprintf(stderr, "bytecode: %zu bytes (source was %u)\n", size, csson_bundle_len);

    js_free(ctx, buf);
    JS_FreeValue(ctx, fn);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;
}
